apiVersion: v1
kind: Secret
metadata:
  name: ngo-service-secret
type: Opaque
stringData:
  DATABASE_URL: "postgres://admin_ngo:solidarytech2024@ngo-db.c4dsa4yc2inl.us-east-1.rds.amazonaws.com/ngo_db"
