apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter-provisioner
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/davsonrsss-devops/fiap-05-GitOps.git'
    targetRevision: HEAD
    path: manifests/karpenter
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
