apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-service
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ngo-service
  template:
    metadata:
      labels:
        app: ngo-service
    spec:
      containers:
        - name: ngo-service
          image: 560985453529.dkr.ecr.us-east-1.amazonaws.com/solidarytech/ngo-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 8081
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: ngo-service-secret
                  key: DATABASE_URL
            - name: OTEL_SERVICE_NAME
              value: "ngo-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.monitoring.svc:4318"
          envFrom:
            - secretRef:
                name: ngo-service-secret

