apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ngo-service
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app: ngo-service
  endpoints:
    - port: http
      path: /metrics
