apiVersion: v1
kind: Service
metadata:
  name: ngo-service
  labels:
    app: ngo-service
spec:
  type: ClusterIP
  selector:
    app: ngo-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8081
