apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# O Reloader geralmente é instalado em um namespace dedicado ou no kube-system, mas vamos isolá-lo aqui.
namespace: reloader

resources:
  - https://raw.githubusercontent.com/stakater/Reloader/master/deployments/kubernetes/reloader.yaml
