apiVersion: v1
kind: Secret
metadata:
  name: volunteer-service-secret
type: Opaque
stringData:
  AWS_DYNAMODB_TABLE: "SolidaryTechVolunteers"
  AWS_REGION: "us-east-1"
  AWS_ACCESS_KEY_ID: "COLE_SUA_CHAVE_AQUI"
  AWS_SECRET_ACCESS_KEY: "COLE_SUA_SECRET_AQUI"
