apiVersion: apps/v1
kind: Deployment
metadata:
  name: donation-service
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: donation-service
  template:
    metadata:
      labels:
        app: donation-service
    spec:
      containers:
        - name: donation-service
          image: 560985453529.dkr.ecr.us-east-1.amazonaws.com/solidarytech/donation-service:latest
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          ports:
            - containerPort: 8082
          env:
            - name: OTEL_SERVICE_NAME
              value: "donation-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://tempo.monitoring.svc:4318"
          envFrom:
            - secretRef:
                name: donation-service-secret
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
