apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: donation-service-es
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: donation-service-secret
    creationPolicy: Owner
  data:
    - secretKey: DATABASE_URL
      remoteRef:
        key: solidarytech/donation-env
        property: DATABASE_URL
    - secretKey: AWS_SQS_URL
      remoteRef:
        key: solidarytech/donation-env
        property: AWS_SQS_URL
    - secretKey: AWS_REGION
      remoteRef:
        key: solidarytech/donation-env
        property: AWS_REGION
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: solidarytech/donation-env
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: solidarytech/donation-env
        property: AWS_SECRET_ACCESS_KEY
